### PR TITLE
Revert "BOOS-3494: prevent NoMethodError Exception that will stall the l...

### PR DESCRIPTION
**Pull request by josephgrossberg**
Reverts boosterllc/video_parser#2

:-1:  This code should not be merged in this state.

There is way too much logic in one line: 
* assignment to ``@video_id``
* assignment to ``matched_data``
* conditional ``if`` statement
* regular expression execution

``matched_data`` is an unclear variable name too (it's all data).

@afifsohaili You should not have approved.

@wsalim please change to something more readable:

```
matched_url_parts = @url.match(/youtube.com\/v\/(?<id>[^?]*)/)
if matched_url_parts
  @video_id ||= matched_url_parts[:id]
end
```

Also, consider writing tests.

### CODE REVIEW

**Comment by wsalim** [comment]
@josephgrossberg  Thanks

I prefer below, at least it will not call the match if the video_id is set

if @video_id.blank? and matched_url_parts = @url.match(/youtube.com\/v\/(?<id>[^?]*)/)
  @video_id = matched_url_parts[:id]
end

**Comment by josephgrossberg** [comment]
If you prefer that style, we can do this:

```
if @video_id.blank?
  matched_url_parts = @url.match(/youtube.com\/v\/(?<id>[^?]*)/)
  if matched_url_parts
    @video_id = matched_url_parts[:id]
  end
end
```

**Comment by wsalim** [comment]
@josephgrossberg Thanks :+1:

**Comment by wsalim** [comment]
Using https://github.com/boosterllc/video_parser/pull/4

**Pull request closed without merging**
