### PR TITLE
BOOS-3511: update video parser version in gemfile.lock

### PR DESCRIPTION
**Pull request by iqbalhasnan**
@victorngkp it does the same thing

I ran bundle install video_parser

### CODE REVIEW

**Comment by cherwei** [comment]
did you update your main app's gemfile.lock to 1.0.1?

**Comment by iqbalhasnan** [comment]
@cherwei can you guide me the right path? I fix this error https://github.com/boosterllc/video_parser/pull/4#discussion_r22916647 and update some of the test cases.

I already bumped the version in version.rb file into 1.0.1.. how do i update the gem version in Gemfil.lock?

**Comment by afifsohaili** [comment]
try running `bundle update --source video_parser`?

**Comment by afifsohaili** [comment]
```bash
Installing jwt 1.2.0
Installing simple_oauth 0.3.1 (was 0.1.9)
Installing multipart-post 2.0.0 (was 1.2.0)
Installing excon 0.43.0
Installing faraday 0.9.1 (was 0.7.6)
Installing oauth2 1.0.0 (was 0.5.2)
Installing youtube_it 2.4.2 (was 2.1.4)
Using video_parser 1.0.1 (was 1.0.0) from git@github.com:boosterllc/video_parser.git (at master)
Your bundle is updated!
```
Tried that and I got this ^

**Comment by iqbalhasnan** [comment]
@afifsohaili yup, that's how I bumped the version..but Victor does't want the other gem got updated..which is impossibru

Victor only want this line video_parser (1.0.0) to get updated to 1.0.1 @victorngkp

**Comment by cherwei** [comment]
Let me trying to understand, you want to update the app 'backend' to have video_parser 1.0.1, am i right? (if i understand you correctly)

You just need to update the backend gem file.lock to 1.0.1

**Comment by iqbalhasnan** [comment]
@cherwei Correct. here is the pull request https://github.com/boosterllc/backend/pull/113/files

For some reasons, Victor is not comfortable when other gems got updated too in that PR, Faraday, Oauth2 etc.

and for some reasons, the gemfile.lock for video parser is still 1.0.0 https://github.com/boosterllc/video_parser/blob/master/Gemfile.lock#L4.. 

So, I ran the bundle update video_parse and PR this branch

**Comment by victorngkp** [comment]
Yupp. Cos the fix on this gem is specifically video_parser code fix (see Jan 13 and 14 commits in https://github.com/boosterllc/video_parser/commits/master), not other dependent gem fix, so we should not update other gem dependencies unnecessarily.

**Comment by cherwei** [comment]
k, you will need to set the version in gemspec to the specific version you want.

**Pull request closed without merging**
