### PR TITLE
BOOS-3494: prevent NoMethodError Exception that will stall the loading of Dashboard and saving of donation campaign

### PR DESCRIPTION
**Pull request by wsalim**
BOOS-3494: prevent NoMethodError Exception that will stall the loading of Dashboard and saving of donation campaign

@afifsohaili, please kindly review

### CODE REVIEW

**Comment by afifsohaili** [comment]
:shipit:

**Comment by josephgrossberg** [comment]
@wsalim and @afifsohaili I have reverted this; it should not have been approved and merged; even if it fixes the Exception, it leaves the code in a far less readable state.

Please see: https://github.com/boosterllc/video_parser/pull/2

**Comment by wsalim** [comment]
@josephgrossberg , would you mind to recommend ?

**Comment by josephgrossberg** [comment]
See my feedback here: https://github.com/boosterllc/video_parser/pull/3

Write clearer code.

Write tests.

**Pull request merged**
